version: '3'

vars:
  APK: app/build/outputs/apk/debug/app-debug.apk
  AVD: Pixel_7_API_35
  WIN_PROJECT: C:\Users\{{.USERNAME}}\projects\launcher

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # WSL/Linux tasks (use ./gradlew)
  fmt:
    desc: Format code (WSL/Linux)
    cmds:
      - uv run ruff check . --fix
      - uv run ruff format .

  test:
    desc: Run unit tests (WSL/Linux)
    cmds:
      - ./gradlew testDebugUnitTest

  lint:
    desc: Run lint checks (WSL/Linux)
    cmds:
      - ./gradlew lint

  build:
    desc: Build debug APK (WSL/Linux)
    cmds:
      - ./gradlew assembleDebug

  clean:
    desc: Clean build artifacts (WSL/Linux)
    cmds:
      - ./gradlew clean

  full:
    desc: Format, lint, test, and build (WSL/Linux)
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: build

  commit:
    desc: Commit with message (use -- MESSAGE="msg")
    cmds:
      - git add .
      - git commit -m "{{.MESSAGE}}"

  push:
    desc: Full build, commit, and push (WSL/Linux)
    cmds:
      - task: full
      - task: commit
        vars: {MESSAGE: "{{.MESSAGE}}"}
      - git push

  # Windows-specific tasks
  win-setup:
    desc: Copy project to Windows side
    cmds:
      - powershell -c "New-Item -ItemType Directory -Force -Path C:\Users\$env:USERNAME\projects"
      - powershell -c "Copy-Item -Recurse -Force . C:\Users\$env:USERNAME\projects\launcher"
      - echo "Project copied to C:\Users\$env:USERNAME\projects\launcher"

  win-build:
    desc: Build APK on Windows side
    dir: C:\Users\{{env "USERNAME"}}\projects\launcher
    cmds:
      - powershell -c ".\gradlew.bat assembleDebug"

  win-emu:
    desc: Start emulator and install APK (Windows)
    cmds:
      - powershell -c "Start-Process -FilePath $env:ANDROID_HOME\emulator\emulator.exe -ArgumentList '-avd {{.AVD}} -no-snapshot-load -no-audio' -NoNewWindow"
      - powershell -c "Start-Sleep -Seconds 30"
      - powershell -c "adb wait-for-device"
      - powershell -c "adb shell 'while [ \"`$(getprop sys.boot_completed)\" != \"1\" ]; do sleep 1; done'"
      - powershell -c "adb install -r {{.APK}}"
      - echo "Ready. Run 'task log' to capture logs"

  # Shared tasks
  log:
    desc: Capture logcat to crash.log
    cmds:
      - adb logcat -c
      - adb logcat > crash.log

  install:
    desc: Install APK on connected device
    cmds:
      - adb install -r {{.APK}}

  # Hybrid workflow (WSL build + Windows emulator)
  emu:
    desc: Build in WSL, run emulator on Windows
    cmds:
      - ./gradlew assembleDebug
      - echo "APK built. Use 'task win-emu' on Windows PowerShell to run emulator"