version: '3'

vars:
  APK: app/build/outputs/apk/debug/app-debug.apk
  AVD: Pixel_7_API_35

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  fmt:
    desc: Format code
    cmds:
      - uv run ruff check . --fix
      - uv run ruff format .

  test:
    desc: Run unit tests
    cmds:
      - gradlew.bat testDebugUnitTest

  lint:
    desc: Run lint checks
    cmds:
      - gradlew.bat lint

  build:
    desc: Build debug APK
    cmds:
      - gradlew.bat assembleDebug

  clean:
    desc: Clean build artifacts
    cmds:
      - gradlew.bat clean

  full:
    desc: Format, lint, test, and build
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: build

  commit:
    desc: Commit with message (use -- MESSAGE="msg")
    cmds:
      - git add .
      - git commit -m "{{.MESSAGE}}"

  push:
    desc: Full build, commit, and push
    cmds:
      - task: full
      - task: commit
        vars: {MESSAGE: "{{.MESSAGE}}"}
      - git push

  emu:
    desc: Start emulator and install APK
    cmds:
      - task: build
      - $ANDROID_HOME/emulator/emulator -avd {{.AVD}} -no-snapshot-load -no-audio &
      - sleep 30
      - adb wait-for-device
      - adb shell 'while [ "$(getprop sys.boot_completed)" != "1" ]; do sleep 1; done'
      - adb install -r {{.APK}}
      - echo "Ready. Run 'task log' to capture logs"

  log:
    desc: Capture logcat to crash.log
    cmds:
      - adb logcat -c
      - adb logcat > crash.log

  install:
    desc: Install APK on connected device
    cmds:
      - adb install -r {{.APK}}