version: '3'
vars:
    GRADLE: ./gradlew
tasks:
    build:
        cmds:
            - uv run ruff check . --fix
            - uv run ruff format .
            - "{{.GRADLE}} lint"
            - "{{.GRADLE}} clean build"
            - git add .
            - git commit -m "{{.MESSAGE}}"