version: '3'

vars:
  APK: app/build/outputs/apk/debug/app-debug.apk
  AVD: Pixel_7_API_35
  PKG: com.kafka.launcher.debug

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # WSL/Linux tasks
  fmt:
    desc: Format code
    cmds:
      - uv run ruff check . --fix
      - uv run ruff format .

  test:
    desc: Run unit tests
    cmds:
      - ./gradlew testDebugUnitTest

  lint:
    desc: Run lint checks
    cmds:
      - ./gradlew lint

  build:
    desc: Build debug APK
    cmds:
      - ./gradlew assembleDebug

  clean:
    desc: Clean build artifacts
    cmds:
      - ./gradlew clean

  full:
    desc: Format, lint, test, and build
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: build

  commit:
    desc: Commit with message (use -- MESSAGE="msg")
    cmds:
      - git add .
      - git commit -m "{{.MESSAGE}}"

  push:
    desc: Full build, commit, and push
    cmds:
      - task: full
      - task: commit
        vars: {MESSAGE: "{{.MESSAGE}}"}
      - git push

  # Windows tasks (run from Windows PowerShell)
  win-setup:
    desc: Copy project to Windows side
    cmds:
      - powershell -c "New-Item -ItemType Directory -Force -Path C:\\Users\\$env:USERNAME\\projects"
      - powershell -c "Copy-Item -Recurse -Force . C:\\Users\\$env:USERNAME\\projects\\launcher"
      - echo "Project copied to C:\\Users\\$env:USERNAME\\projects\\launcher"

  win-emu:
    desc: Start emulator (Windows only)
    cmds:
      - powershell -c "Start-Process -FilePath $env:ANDROID_HOME\\emulator\\emulator.exe -ArgumentList '-avd {{.AVD}} -no-snapshot-load -no-audio' -NoNewWindow"
      - echo "Emulator starting... Wait for boot to complete"

  win-build:
    desc: Build APK (Windows only)
    cmds:
      - powershell -c ".\\gradlew.bat assembleDebug"

  win-install:
    desc: Install APK to emulator (Windows only)
    cmds:
      - powershell -c "adb kill-server; adb start-server"
      - powershell -c "adb wait-for-device"
      - powershell -c "adb install -r {{.APK}}"
      - echo "APK installed successfully"

  win-launch:
    desc: Launch app on emulator (Windows only)
    cmds:
      - powershell -c "adb shell am start -n {{.PKG}}/com.kafka.launcher.MainActivity"

  win-log:
    desc: Capture crash log (Windows only)
    cmds:
      - powershell -c "adb logcat -c"
      - powershell -c "adb logcat > crash.log"

  win-full:
    desc: Complete Windows workflow
    cmds:
      - task: win-build
      - task: win-emu
      - powershell -c "Start-Sleep -Seconds 40"
      - task: win-install
      - task: win-launch
      - echo "App launched. Run 'task win-log' if needed"

  # Shared tasks
  install:
    desc: Install APK on connected device
    cmds:
      - adb install -r {{.APK}}

  launch:
    desc: Launch app on connected device
    cmds:
      - adb shell am start -n {{.PKG}}/com.kafka.launcher.MainActivity

  log:
    desc: Capture logcat to crash.log
    cmds:
      - adb logcat -c
      - adb logcat > crash.log