package com.kafka.launcher.config

object AppSearchConfig {
    val aliases = mapOf(
        "twitter" to listOf("x"),
        "tweet" to listOf("x"),
        "bird" to listOf("x"),
        "insta" to listOf("instagram"),
        "ig" to listOf("instagram"),
        "fb" to listOf("facebook"),
        "yt" to listOf("youtube"),
        "tube" to listOf("youtube"),
        "gmap" to listOf("maps"),
        "mail" to listOf("gmail"),
        "msg" to listOf("messages", "messenger"),
        "pic" to listOf("photos", "gallery"),
        "cam" to listOf("camera"),
        "net" to listOf("chrome", "browser", "internet"),
        "web" to listOf("chrome", "browser", "internet"),
        "store" to listOf("play store", "app store"),
        "shop" to listOf("amazon", "rakuten"),
        "pay" to listOf("wallet", "pay"),
        "music" to listOf("spotify", "youtube music", "music"),
        "song" to listOf("spotify", "youtube music", "music"),
        "chat" to listOf("discord", "line", "slack", "whatsapp", "telegram"),
        "dc" to listOf("discord"),
        "line" to listOf("line"),
        "paypay" to listOf("paypay"),
        "ペイペイ" to listOf("paypay"),
        "rakuten pay" to listOf("rakuten pay", "楽天ペイ"),
        "楽天ペイ" to listOf("楽天ペイ", "rakuten pay"),
        "au pay" to listOf("au pay", "aupay"),
        "aupay" to listOf("au pay", "aupay"),
        "d払い" to listOf("d払い", "d pay"),
        "dbarai" to listOf("d払い", "d pay"),
        "d pay" to listOf("d払い", "d pay"),
        "merpay" to listOf("merpay", "メルペイ"),
        "メルペイ" to listOf("メルペイ", "merpay"),
        "line pay" to listOf("line pay", "ラインペイ"),
        "ラインペイ" to listOf("ラインペイ", "line pay"),
        "famipay" to listOf("ファミペイ"),
        "ファミペイ" to listOf("ファミペイ"),
        "nanaco" to listOf("nanaco"),
        "waon" to listOf("waon"),
        "suica" to listOf("suica"),
        "mufg" to listOf("ufj", "三菱"),
        "ufj" to listOf("ufj", "三菱"),
        "三菱" to listOf("ufj"),
        "smbc" to listOf("三井住友"),
        "三井住友" to listOf("三井住友"),
        "mizuho" to listOf("みずほ"),
        "みずほ" to listOf("みずほ"),
        "sbi" to listOf("sbi", "住信"),
        "住信" to listOf("住信"),
        "rakuten bank" to listOf("楽天銀行"),
        "楽天銀行" to listOf("楽天銀行"),
        "paypay bank" to listOf("paypay銀行"),
        "ゆうちょ" to listOf("ゆうちょ"),
        "japan post" to listOf("ゆうちょ"),
        "moneyforward" to listOf("マネーフォワード"),
        "マネーフォワード" to listOf("マネーフォワード"),
        "zaim" to listOf("zaim")
    )
}
